version: '3.8'

services:
  # バックエンド
  backend:
    build: ./backend
    ports:
      - "8081:8081"  # ポート8081をホストに公開
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=chat_app_db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: air  # airを使用して開発用サーバーを起動

  # フロントエンド
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev  # 開発用サーバーを起動

  # PostgreSQLデータベース
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chat_app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - chat_app_db_data:/var/lib/postgresql/data

  # pgAdmin（PostgreSQL管理用GUI）
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  chat_app_db_data:
  pgadmin-data:
